name: "Deploy FivemToolsLib"

on:
  push:
    tags:
      - "fivemtoolslib/v*"

permissions:
  contents: write

env:
  PROJECT_PATH: FivemToolsLib.csproj

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        run: nuget restore FivemToolsLib.sln

      - name: Build with MSBuild
        run: msbuild FivemToolsLib.sln /p:Configuration=Release
        
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      
      - uses: csexton/release-asset-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            bin\Release\net452\FivemToolsLib.xml
            bin\Release\net452\FivemToolsLib.dll
          release-url: ${{ steps.create_release.outputs.upload_url }}